library(dplyr) 
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "ElectricPower.zip", method="curl")
unzip("ElectricPower.zip")
ElectricPower <- read.table("household_power_consumption.txt", sep=";", na.strings ="?", header = TRUE, stringsAsFactors = FALSE)
selection <- filter(ElectricPower, Date=="1/2/2007" | Date=="2/2/2007")
FebruaryData <- mutate(selection, DateTime = paste(selection$Date, selection$Time, sep=" "))
FebruaryData <- transform(FebruaryData, DateTime=strptime(DateTime, "%d/%m/%Y %H:%M:%S"))
png(filename="plot2.png", width = 480, height = 480)
plot(FebruaryData$DateTime, FebruaryData$Global_active_power, type="n", xlab="", ylab="Global Active Power (kilowatts)")
lines(FebruaryData$DateTime, FebruaryData$Global_active_power, col="black")
dev.off()
