library(dplyr) 
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "ElectricPower.zip", method="curl")
unzip("ElectricPower.zip")
ElectricPower <- read.table("household_power_consumption.txt", sep=";", na.strings ="?", header = TRUE, stringsAsFactors = FALSE)
ElectricPower <- transform(ElectricPower, Date=as.Date(Date, "%d/%m/%Y"))
MetersFebruary <- filter(ElectricPower, Date=="2007-02-01" | Date=="2007-02-02")
png(filename="plot1.png", width = 480, height = 480)
hist(MetersFebruary$Global_active_power, col="red", xlab = ("Global Active Power (kilowatts)"), main=paste("Global Active Power"))
dev.off()
